import { Tournament, Group, Team, Match, BankAccount, Sponsor } from './types';

export const INITIAL_TOURNAMENT: Tournament = {
  id: 'tourn-shilda-2026',
  name: 'გაუზიარე მომავალს',
  year: 2026,
  location: 'სოფელი შილდის სტადიონი',
  description: 'სამოყვარულო მინი-ფეხბურთის საქველმოქმედო ტურნირი',
  startDate: '2026-08-22',
  endDate: '2026-08-25',
  status: 'active',
  pointsForWin: 3,
  pointsForDraw: 1,
  pointsForLoss: 0,
  qualificationCount: 4,
};

export const INITIAL_GROUPS: Group[] = [
  { id: 'group-a', tournamentId: 'tourn-shilda-2026', name: 'A ჯგუფი', code: 'A', displayOrder: 1 },
  { id: 'group-b', tournamentId: 'tourn-shilda-2026', name: 'B ჯგუფი', code: 'B', displayOrder: 2 },
];

export const INITIAL_TEAMS: Team[] = [
  // Group A
  { id: 'team-eniseli', groupId: 'group-a', name: 'ენისელი', displayOrder: 1 },
  { id: 'team-sabue', groupId: 'group-a', name: 'საბუე', displayOrder: 2 },
  { id: 'team-telavi', groupId: 'group-a', name: 'თელავი', displayOrder: 3 },
  { id: 'team-shilda', groupId: 'group-a', name: 'შილდა', displayOrder: 4 },
  { id: 'team-gremi', groupId: 'group-a', name: 'გრემი', displayOrder: 5 },
  { id: 'team-kakhelebi', groupId: 'group-a', name: 'კახელები', displayOrder: 6 },
  { id: 'team-peniksi', groupId: 'group-a', name: 'ფენიქსი', displayOrder: 7 },

  // Group B
  { id: 'team-kalauri', groupId: 'group-b', name: 'კალაური', displayOrder: 1 },
  { id: 'team-vazisubani', groupId: 'group-b', name: 'ვაზისუბანი', displayOrder: 2 },
  { id: 'team-shilda-2', groupId: 'group-b', name: 'შილდა 2', displayOrder: 3 },
  { id: 'team-gavazi', groupId: 'group-b', name: 'გავაზი', displayOrder: 4 },
  { id: 'team-lopota', groupId: 'group-b', name: 'ლოპოტა', displayOrder: 5 },
  { id: 'team-klubis-ubani', groupId: 'group-b', name: 'კლუბის უბანი', displayOrder: 6 },
  { id: 'team-tsnori', groupId: 'group-b', name: 'წნორი', displayOrder: 7 },

  // Special Exhibition Team
  { id: 'team-allstars', groupId: '', name: 'ტურნირის ნაკრები', displayOrder: 99 },
];

export const INITIAL_MATCHES: Match[] = [
  {
    "id": "m-d1-1",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-shilda-2",
    "awayTeamId": "team-kalauri",
    "scheduledAt": "19:00",
    "status": "finished",
    "homeScore": 1,
    "awayScore": 0,
    "roundType": "group",
    "matchDay": 1
  },
  {
    "id": "m-d1-2",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-eniseli",
    "awayTeamId": "team-sabue",
    "scheduledAt": "19:30",
    "status": "finished",
    "homeScore": 2,
    "awayScore": 1,
    "roundType": "group",
    "matchDay": 1
  },
  {
    "id": "m-d1-3",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-vazisubani",
    "awayTeamId": "team-lopota",
    "scheduledAt": "20:00",
    "status": "finished",
    "homeScore": 8,
    "awayScore": 1,
    "roundType": "group",
    "matchDay": 1
  },
  {
    "id": "m-d1-4",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-shilda",
    "awayTeamId": "team-gremi",
    "scheduledAt": "20:30",
    "status": "finished",
    "homeScore": 2,
    "awayScore": 0,
    "roundType": "group",
    "matchDay": 1
  },
  {
    "id": "m-d1-5",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-tsnori",
    "awayTeamId": "team-klubis-ubani",
    "scheduledAt": "21:00",
    "status": "finished",
    "homeScore": 4,
    "awayScore": 1,
    "roundType": "group",
    "matchDay": 1
  },
  {
    "id": "m-d1-6",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-telavi",
    "awayTeamId": "team-kakhelebi",
    "scheduledAt": "21:30",
    "status": "finished",
    "homeScore": 2,
    "awayScore": 2,
    "roundType": "group",
    "matchDay": 1
  },
  {
    "id": "m-d1-7",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-gavazi",
    "awayTeamId": "team-kalauri",
    "scheduledAt": "22:00",
    "status": "finished",
    "homeScore": 3,
    "awayScore": 3,
    "roundType": "group",
    "matchDay": 1
  },
  {
    "id": "m-d1-8",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-shilda",
    "awayTeamId": "team-peniksi",
    "scheduledAt": "22:30",
    "status": "finished",
    "homeScore": 7,
    "awayScore": 3,
    "roundType": "group",
    "matchDay": 1
  },
  {
    "id": "m-d1-9",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-vazisubani",
    "awayTeamId": "team-tsnori",
    "scheduledAt": "23:00",
    "status": "finished",
    "homeScore": 3,
    "awayScore": 4,
    "roundType": "group",
    "matchDay": 1
  },
  {
    "id": "m-d2-1",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-gremi",
    "awayTeamId": "team-peniksi",
    "scheduledAt": "18:30",
    "status": "finished",
    "homeScore": 7,
    "awayScore": 1,
    "roundType": "group",
    "matchDay": 2
  },
  {
    "id": "m-d2-2",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-klubis-ubani",
    "awayTeamId": "team-gavazi",
    "scheduledAt": "19:00",
    "status": "finished",
    "homeScore": 4,
    "awayScore": 2,
    "roundType": "group",
    "matchDay": 2
  },
  {
    "id": "m-d2-3",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-shilda-2",
    "awayTeamId": "team-lopota",
    "scheduledAt": "19:30",
    "status": "finished",
    "homeScore": 4,
    "awayScore": 1,
    "roundType": "group",
    "matchDay": 2
  },
  {
    "id": "m-d2-4",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-kakhelebi",
    "awayTeamId": "team-eniseli",
    "scheduledAt": "20:00",
    "status": "finished",
    "homeScore": 3,
    "awayScore": 1,
    "roundType": "group",
    "matchDay": 2
  },
  {
    "id": "m-d2-5",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-telavi",
    "awayTeamId": "team-sabue",
    "scheduledAt": "20:30",
    "status": "finished",
    "homeScore": 4,
    "awayScore": 1,
    "roundType": "group",
    "matchDay": 2
  },
  {
    "id": "m-d2-6",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-gavazi",
    "awayTeamId": "team-tsnori",
    "scheduledAt": "21:00",
    "status": "finished",
    "homeScore": 4,
    "awayScore": 2,
    "roundType": "group",
    "matchDay": 2
  },
  {
    "id": "m-d2-7",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-shilda",
    "awayTeamId": "team-kakhelebi",
    "scheduledAt": "21:30",
    "status": "finished",
    "homeScore": 3,
    "awayScore": 1,
    "roundType": "group",
    "matchDay": 2
  },
  {
    "id": "m-d2-8",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-lopota",
    "awayTeamId": "team-kalauri",
    "scheduledAt": "22:00",
    "status": "finished",
    "homeScore": 1,
    "awayScore": 2,
    "roundType": "group",
    "matchDay": 2
  },
  {
    "id": "m-d2-9",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-vazisubani",
    "awayTeamId": "team-klubis-ubani",
    "scheduledAt": "22:30",
    "status": "finished",
    "homeScore": 1,
    "awayScore": 4,
    "roundType": "group",
    "matchDay": 2
  },
  {
    "id": "m-d2-10",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-gremi",
    "awayTeamId": "team-sabue",
    "scheduledAt": "23:00",
    "status": "finished",
    "homeScore": 3,
    "awayScore": 1,
    "roundType": "group",
    "matchDay": 2
  },
  {
    "id": "m-d3-1",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-kalauri",
    "awayTeamId": "team-vazisubani",
    "scheduledAt": "18:30",
    "status": "finished",
    "homeScore": 9,
    "awayScore": 3,
    "roundType": "group",
    "matchDay": 3
  },
  {
    "id": "m-d3-2",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-eniseli",
    "awayTeamId": "team-peniksi",
    "scheduledAt": "19:00",
    "status": "finished",
    "homeScore": 4,
    "awayScore": 1,
    "roundType": "group",
    "matchDay": 3
  },
  {
    "id": "m-d3-3",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-shilda-2",
    "awayTeamId": "team-klubis-ubani",
    "scheduledAt": "19:30",
    "status": "finished",
    "homeScore": 5,
    "awayScore": 0,
    "roundType": "group",
    "matchDay": 3
  },
  {
    "id": "m-d3-4",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-telavi",
    "awayTeamId": "team-gremi",
    "scheduledAt": "20:00",
    "status": "finished",
    "homeScore": 2,
    "awayScore": 2,
    "roundType": "group",
    "matchDay": 3
  },
  {
    "id": "m-d3-5",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-tsnori",
    "awayTeamId": "team-lopota",
    "scheduledAt": "20:30",
    "status": "finished",
    "homeScore": 4,
    "awayScore": 1,
    "roundType": "group",
    "matchDay": 3
  },
  {
    "id": "m-d3-6",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-shilda-2",
    "awayTeamId": "team-vazisubani",
    "scheduledAt": "21:00",
    "status": "finished",
    "homeScore": 5,
    "awayScore": 1,
    "roundType": "group",
    "matchDay": 3
  },
  {
    "id": "m-d3-7",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-sabue",
    "awayTeamId": "team-shilda",
    "scheduledAt": "21:30",
    "status": "finished",
    "homeScore": 0,
    "awayScore": 3,
    "roundType": "group",
    "matchDay": 3
  },
  {
    "id": "m-d3-8",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-gremi",
    "awayTeamId": "team-eniseli",
    "scheduledAt": "22:00",
    "status": "finished",
    "homeScore": 2,
    "awayScore": 1,
    "roundType": "group",
    "matchDay": 3
  },
  {
    "id": "m-d3-9",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-gavazi",
    "awayTeamId": "team-lopota",
    "scheduledAt": "22:30",
    "status": "finished",
    "homeScore": 4,
    "awayScore": 3,
    "roundType": "group",
    "matchDay": 3
  },
  {
    "id": "m-d3-10",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-kakhelebi",
    "awayTeamId": "team-sabue",
    "scheduledAt": "23:00",
    "status": "finished",
    "homeScore": 1,
    "awayScore": 0,
    "roundType": "group",
    "matchDay": 3
  },
  {
    "id": "m-d3-11",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-telavi",
    "awayTeamId": "team-peniksi",
    "scheduledAt": "23:30",
    "status": "finished",
    "homeScore": 3,
    "awayScore": 0,
    "roundType": "group",
    "matchDay": 3
  },
  {
    "id": "m-d4-1",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-kakhelebi",
    "awayTeamId": "team-peniksi",
    "scheduledAt": "18:00",
    "status": "finished",
    "homeScore": 3,
    "awayScore": 0,
    "roundType": "group",
    "matchDay": 4
  },
  {
    "id": "m-d4-2",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-gavazi",
    "awayTeamId": "team-vazisubani",
    "scheduledAt": "18:30",
    "status": "finished",
    "homeScore": 3,
    "awayScore": 0,
    "roundType": "group",
    "matchDay": 4
  },
  {
    "id": "m-d4-3",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-lopota",
    "awayTeamId": "team-klubis-ubani",
    "scheduledAt": "19:00",
    "status": "finished",
    "homeScore": 0,
    "awayScore": 3,
    "roundType": "group",
    "matchDay": 4
  },
  {
    "id": "m-d4-4",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-tsnori",
    "awayTeamId": "team-kalauri",
    "scheduledAt": "19:30",
    "status": "finished",
    "homeScore": 1,
    "awayScore": 2,
    "roundType": "group",
    "matchDay": 4
  },
  {
    "id": "m-d4-5",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-kakhelebi",
    "awayTeamId": "team-gremi",
    "scheduledAt": "20:00",
    "status": "finished",
    "homeScore": 1,
    "awayScore": 0,
    "roundType": "group",
    "matchDay": 4
  },
  {
    "id": "m-d4-6",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-shilda-2",
    "awayTeamId": "team-tsnori",
    "scheduledAt": "20:30",
    "status": "finished",
    "homeScore": 0,
    "awayScore": 1,
    "roundType": "group",
    "matchDay": 4
  },
  {
    "id": "m-d4-7",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-eniseli",
    "awayTeamId": "team-telavi",
    "scheduledAt": "21:00",
    "status": "finished",
    "homeScore": 1,
    "awayScore": 3,
    "roundType": "group",
    "matchDay": 4
  },
  {
    "id": "m-d4-8",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-gavazi",
    "awayTeamId": "team-shilda-2",
    "scheduledAt": "21:30",
    "status": "finished",
    "homeScore": 2,
    "awayScore": 1,
    "roundType": "group",
    "matchDay": 4
  },
  {
    "id": "m-d4-9",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-telavi",
    "awayTeamId": "team-shilda",
    "scheduledAt": "22:00",
    "status": "finished",
    "homeScore": 2,
    "awayScore": 0,
    "roundType": "group",
    "matchDay": 4
  },
  {
    "id": "m-d4-10",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-b",
    "homeTeamId": "team-klubis-ubani",
    "awayTeamId": "team-kalauri",
    "scheduledAt": "22:30",
    "status": "finished",
    "homeScore": 1,
    "awayScore": 4,
    "roundType": "group",
    "matchDay": 4
  },
  {
    "id": "m-d4-11",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-sabue",
    "awayTeamId": "team-peniksi",
    "scheduledAt": "23:00",
    "status": "finished",
    "homeScore": 3,
    "awayScore": 0,
    "roundType": "group",
    "matchDay": 4
  },
  {
    "id": "m-d4-12",
    "tournamentId": "tourn-shilda-2026",
    "groupId": "group-a",
    "homeTeamId": "team-shilda",
    "awayTeamId": "team-eniseli",
    "scheduledAt": "23:30",
    "status": "finished",
    "homeScore": 3,
    "awayScore": 0,
    "roundType": "group",
    "matchDay": 4
  },
  {
    "id": "m-qf-1",
    "tournamentId": "tourn-shilda-2026",
    "bracketPosition": "QF1",
    "homeTeamId": "team-shilda",
    "awayTeamId": "team-tsnori",
    "scheduledAt": "TBD",
    "status": "finished",
    "homeScore": 7,
    "awayScore": 3,
    "roundType": "quarter_final",
    "startedAt": "2026-08-27T15:54:27.994Z",
    "finishedAt": "2026-08-27T16:37:39.219Z"
  },
  {
    "id": "m-qf-2",
    "tournamentId": "tourn-shilda-2026",
    "bracketPosition": "QF2",
    "homeTeamId": "team-kakhelebi",
    "awayTeamId": "team-gavazi",
    "scheduledAt": "TBD",
    "status": "finished",
    "homeScore": 0,
    "awayScore": 3,
    "roundType": "quarter_final",
    "startedAt": "2026-08-26T17:12:53.057Z",
    "hasPenalties": false,
    "finishedAt": "2026-08-26T17:13:25.555Z",
    "matchDay": 1
  },
  {
    "id": "m-qf-3",
    "tournamentId": "tourn-shilda-2026",
    "bracketPosition": "QF3",
    "homeTeamId": "team-kalauri",
    "awayTeamId": "team-gremi",
    "scheduledAt": "TBD",
    "status": "finished",
    "homeScore": 3,
    "awayScore": 3,
    "roundType": "quarter_final",
    "startedAt": "2026-08-26T16:15:04.723Z",
    "hasPenalties": true,
    "homePenaltyScore": 5,
    "awayPenaltyScore": 4,
    "finishedAt": "2026-08-26T16:58:16.638Z"
  },
  {
    "id": "m-qf-4",
    "tournamentId": "tourn-shilda-2026",
    "bracketPosition": "QF4",
    "homeTeamId": "team-shilda-2",
    "awayTeamId": "team-telavi",
    "scheduledAt": "TBD",
    "status": "finished",
    "homeScore": 1,
    "awayScore": 4,
    "roundType": "quarter_final",
    "startedAt": "2026-08-26T17:44:45.102Z",
    "finishedAt": "2026-08-26T22:06:34.783Z"
  },
  {
    "id": "m-sf-2",
    "tournamentId": "tourn-shilda-2026",
    "bracketPosition": "SF2",
    "roundType": "semi_final",
    "homeTeamId": "team-kalauri",
    "awayTeamId": "team-telavi",
    "scheduledAt": "TBD",
    "status": "finished",
    "homeScore": 1,
    "awayScore": 5,
    "startedAt": "2026-08-27T16:39:30.298Z",
    "finishedAt": "2026-08-27T17:10:09.553Z"
  },
  {
    "id": "m-sf-1",
    "tournamentId": "tourn-shilda-2026",
    "bracketPosition": "SF1",
    "roundType": "semi_final",
    "homeTeamId": "team-shilda",
    "awayTeamId": "team-gavazi",
    "scheduledAt": "TBD",
    "status": "finished",
    "homeScore": 5,
    "awayScore": 0,
    "hasPenalties": false,
    "startedAt": "2026-08-27T17:16:50.510Z",
    "finishedAt": "2026-08-27T17:54:27.801Z"
  },
  {
    "id": "m-friendly",
    "tournamentId": "tourn-shilda-2026",
    "bracketPosition": "FRIENDLY",
    "roundType": "friendly",
    "homeTeamId": "team-shilda-2",
    "awayTeamId": "team-allstars",
    "scheduledAt": "5 სექტემბერი, 20:00",
    "status": "scheduled",
    "homeScore": 0,
    "awayScore": 0,
    "matchDay": 5
  },
  {
    "id": "m-final",
    "tournamentId": "tourn-shilda-2026",
    "bracketPosition": "FINAL",
    "roundType": "final",
    "homeTeamId": "team-shilda",
    "awayTeamId": "team-telavi",
    "scheduledAt": "5 სექტემბერი, 21:00",
    "status": "scheduled",
    "homeScore": 0,
    "awayScore": 0,
    "matchDay": 5
  },
  {
    "id": "m-third",
    "tournamentId": "tourn-shilda-2026",
    "bracketPosition": "THIRD_PLACE",
    "roundType": "third_place",
    "homeTeamId": "team-gavazi",
    "awayTeamId": "team-kalauri",
    "scheduledAt": "TBD",
    "status": "finished",
    "homeScore": 0,
    "awayScore": 4,
    "hasPenalties": false,
    "matchDay": 1
  }
];

export const BANK_ACCOUNTS: BankAccount[] = [
  {
    bankName: 'თიბისი ბანკი (TBC Bank)',
    accountNumber: 'GE37TB7822045068100056',
    recipient: 'გიორგი ფაჩოშვილი',
    purpose: 'გუნდის სახელი ან „ქველმოქმედება“',
    icon: 'tbc',
  },
  {
    bankName: 'საქართველოს ბანკი (Bank of Georgia)',
    accountNumber: 'GE91BG0000000611281144',
    recipient: 'გიორგი ფაჩოშვილი',
    purpose: 'გუნდის სახელი ან „ქველმოქმედება“',
    icon: 'bog',
  },
];

export const CONTACT_PHONES = ['592707116', '599431666'];
export const CONTACT_PHONES_FORMATTED = ['592 707 116', '599 431 666'];

export const REGISTRATION_FORM_URL = 'https://forms.gle/xLE8MkWKuzk8vQC9A';
export const FACEBOOK_EVENT_URL = 'https://www.facebook.com/events/27225896957084153';
export const FACEBOOK_PAGE_URL = 'https://www.facebook.com/profile.php?id=61550476371001&sk=about';

export const PARTNER_EUROPHARM: Sponsor = {
  name: 'აფთიაქი „ევროფარმი“',
  role: 'ტურნირის ტრადიციული მხარდამჭერი',
  description: 'მთავარი საპრიზო პარტნიორი I ადგილის მფლობელი გუნდისთვის',
};
